#!/usr/bin/env bash
# Set the desired key name and bits

KEY_NAME="school"
BITS=4096

# Generate the RSA key pair
ssh-keygen -t rsa -b $BITS -C "$KEY_NAME" -f $KEY_NAME

# Inform user about successful key generation
echo "RSA key pair successfully generated."

